arch:
  - amd64
  - ppc64le
dist: xenial
language: python
cache:
  - pip
python:
  - '3.7'
  - '3.6'
  - '3.5'
before_install:
  # This is a permission fix meant only for Travis base image for PPC64LE.
  # It is a known issue and required before installing python dependencies, except for bionic.
  - |
    if [[ "${TRAVIS_CPU_ARCH}" == "ppc64le" ]]; then
      sudo chown -R $USER:$GROUP ~/.cache/pip/wheels;
    fi
  - pip install -U pip
  - pip install -U setuptools
  - pip install -U wheel
  - pip install -U twine
install:
  - pip install tox-travis .[devel]
script:
  # Check packaging (README format etc...)
  - pip install -U setuptools
  - pip install -U wheel
  - pip install -U twine
  - pip list
  - rm -rf dist
  - python setup.py sdist
  - python setup.py bdist_wheel
  - twine check dist/*
  # Execture tests
  - tox
  # While many deltas exists between python-podman version and libpod version
  # we ask to synchronize.sh to don't exit "1" to avoid to get lot of
  # well know issues, in other word we will only display errors in CI job log
  # but we will consider that everything work fine with that.
  - ./tools/synchronize.sh --ignore
deploy:
  - provider: pypi
    user: containers-libpod
    password:
      secure: "C88DmalsYjwtUrjWWyEeeKtLa9Q0VXlCCoCDguNOhZFmroW3DsOxZZmHBEEK3fN2QCfE5asR4zMNMpszqg324ubY6gmfy+PHVOnsLVZf4B2ZV96vhGrElk99YfgblYidwqB0L84AxK6n54iX5KFQj/8WWfkTqnPrGcA6pGX5C332uKpQoW40k/OCSbdD0C/FzaTLvgH+rUxAhamu2I2k/qJFUr6uQ5flgIJyQJcgVCvN0dP4Yyx9eSRpuWbApn0NkHOSmXJD3I2YWEf5LCSjTiyDGuQlja2rOgLynoSgBa1t8ZFXSb/nenSunAAy2y1KOcrn7qCfc56V7NwcQ+RIXT7LlSU/e2GgwHlXXsRCpZOrBcKJu3tTlVsrxpk5aXg1+boKwl2T4NEjJERskmENT2TJyZFJMr3/XAdHtnuKZcqydO/CPIqIbfRfDSN2+/8J++I1zQa5+lDXjiA/Qs7gzCW2DLZIzvzT3bD1zQPWDAP2pmixLDOY6e29jMW5pqnJazU+mrJSwOKN6e5pe5dAKx436XFByK7HZhptmkFbP5LL0HnDO6VjK4QyF1KYnBV/S4Y58FyO2jOgXA7feYaybzzbzjRbooKiqG+GC0J76GSu7dd/pqTRWVYTEn37B+No7v5HEzTP1dnQWPPynppwyBMrtT1tqsRGyEmJnm7Ml/8="
    on:
      tags: true
    distributions: sdist bdist_wheel
    skip_existing: true
